### ISSUE TITLE
Can we parse TypeScript Repositories for getting function, docstring pair ?

### ISSUE THREAD

**Issue by Manas-Embold** [ncoop57/function_parser#4]
I know, typescript is not supported, but can we pass language as javascript ?
would that help ?

Basically I need function, docstring pair for typescript repos for a research project, I am not sure if that is something similar to javascript parsing.

**Comment by ncoop57** [comment]
not entirely sure if that would work. My guess is that for most functions it would since function declarations are pretty similar between javascript and typescript, but there may be some edge cases where it fails. If you've tried it out and it worked please let me know, I'd be interested to know!

**Comment by frederik-markus** [comment]
Hi there, I am currently looking to do the same thing. Have you managed to pass typescript?
