### ISSUE TITLE
How to use the function_parser?

### ISSUE THREAD

**Issue by skye95git** [ncoop57/function_parser#5]
When I run 

`pip install function-parser`

there is an error:
<img width="819" alt="捕获6" src="https://user-images.githubusercontent.com/41561936/128824590-972ffae3-af52-407d-9a0f-b42a5e35559a.PNG">

What should I do?

**Comment by ncoop57** [comment]
Hi there! Apologies for this issue, I am currently trying to track down the issue as I have been able to reproduce it in one of my environment, but not another. Could you post your pip and python version?

**Comment by skye95git** [comment]
> Hi there! Apologies for this issue, I am currently trying to track down the issue as I have been able to reproduce it in one of my environment, but not another. Could you post your pip and python version?

Thanks for your reply! I have solved this problem by creating an new environment. I meet another questions now:

I want to parse single file into functions. I change `processor.process_dee()` to `processor.process_single_file()`, it works:

<img width="812" alt="微信图片_20210813145628" src="https://user-images.githubusercontent.com/41561936/129317138-8fbd3e7f-5c30-4807-a054-b17972411efa.png">

But the argument to the `processor.process_single_file` function is filepath. My data is different from yours. The file content is saved in dictionary:

<img width="639" alt="微信图片_20210813150030" src="https://user-images.githubusercontent.com/41561936/129317513-b10973dd-8298-4e04-8bb0-73227883317f.png">

I think of two solutions:

The first one: I can save the file content into a file before parsing. I also want to save repo_name and path, so I change `function_parser/function_parser/process.py` :

<img width="740" alt="捕获13" src="https://user-images.githubusercontent.com/41561936/129318609-81fb1bf4-fe0f-418f-b3b9-a8fbcba19bba.PNG">

<img width="579" alt="捕获14" src="https://user-images.githubusercontent.com/41561936/129318632-c89c972d-f2bf-4ec6-96aa-fc3d6af3f4d9.PNG">


The second one: I can change the `processor.process_single_file` function.

<img width="608" alt="微信图片16_20210813151157" src="https://user-images.githubusercontent.com/41561936/129318928-717a17b6-a301-4398-b2f4-d1964d466774.png">

<img width="593" alt="微信图片_20210813151210" src="https://user-images.githubusercontent.com/41561936/129318951-2185f377-aebf-4638-8b3d-6a7196ca041e.png">


But after I changed the `function_parser/function_parser/process.py`, it didn't work. It still use the function_parser in virtual environment. So I don't import function_parser from environment. I just use the project `ncoop57/function_parser` download from github. There is an error: `unhashable type: 'tree_sitter.Node'`. 

What should I do?

**Comment by skye95git** [comment]
> Hi there! Apologies for this issue, I am currently trying to track down the issue as I have been able to reproduce it in one of my environment, but not another. Could you post your pip and python version?

I try to save the source code in content field:

`with open(r'function_parser-main\nbs\test\repo.json','r',encoding='utf8')as fp:
    json_data = json.load(fp)
    print(json_data['content'])
    print(type(json_data['content']))
    repo_path = os.path.join(r"function_parser-main\nbs\test", json_data['repo_name'])
    file_path = os.path.join(repo_path, '/'.join(json_data['repo_name'].split('/')[:-1]))
    os.makedirs(file_path)
    filename = json_data['repo_name'].split('/')[-1]
    file = open(os.path.join(file_path, filename), "w").write(json_data['content'])`

The .py file has been generated:

<img width="497" alt="捕获20" src="https://user-images.githubusercontent.com/41561936/129338931-ee29517f-5d4d-46c0-b4a7-9e0dffeb6f93.PNG">

But when I parse single file into functions, the result is empty:

<img width="760" alt="捕获21" src="https://user-images.githubusercontent.com/41561936/129339188-e4b5fbd3-58e0-4b90-8958-9d4f5bb23bd0.PNG">

Are generated Python files different from those in repo?

**Comment by ncoop57** [comment]
`unhashable type: 'tree_sitter.Node'`
 This error is due to not using the correct tree_sitter version. I'd recommend creating an entirely new env and making sure to rerun `build_grammars` command.

For your other question, there should not be any difference between generated python files and those in a repository. From what I can see, it looks like you are using jupyter notebook. Could you send me your code (maybe put it into google colab) that way I can better triage the problem?

**Comment by skye95git** [comment]
> `unhashable type: 'tree_sitter.Node'`
> This error is due to not using the correct tree_sitter version. I'd recommend creating an entirely new env and making sure to rerun `build_grammars` command.
> 
> For your other question, there should not be any difference between generated python files and those in a repository. From what I can see, it looks like you are using jupyter notebook. Could you send me your code (maybe put it into google colab) that way I can better triage the problem?

Thanks for your reply! I will try to create an entirely new env and rerun `build_grammars` command.

The second question is very strange. I run the Untitled.ipynb as follow:

#########################
import function_parser
import os
import json

import pandas as pd

from function_parser.language_data import LANGUAGE_METADATA
from function_parser.process import DataProcessor
from tree_sitter import Language

language = "python"
DataProcessor.PARSER.set_language(
    Language(os.path.join("/home/linjiayi/function_parser/nbs/tree-sitter", "tree-sitter-languages.so"), language)
)
processor = DataProcessor(
    language=language, language_parser=LANGUAGE_METADATA[language]["language_parser"]
)


json_data = {
    "repo_name": "Ghalko/waterbutler",
    "ref": "refs/heads/develop",
    "path": "waterbutler/tasks/app.py",
    "copies": "7",
    "content": "from celery import Celery\nfrom celery.signals import task_failure\n\nfrom raven import Client\n\nfrom waterbutler import settings\nfrom waterbutler.tasks import settings as tasks_settings\n\n\napp = Celery()\napp.config_from_object(tasks_settings)\n\n\ndef register_signal(client):\n    \"\"\"Adapted from `raven.contrib.celery.register_signal`. Remove args and\n    kwargs from logs so that keys aren't leaked to Sentry.\n    \"\"\"\n    def process_failure_signal(sender, task_id, *args, **kwargs):\n        client.captureException(\n            extra={\n                'task_id': task_id,\n                'task': sender,\n            }\n        )\n    task_failure.connect(process_failure_signal, weak=False)\n\n\nsentry_dsn = settings.get('SENTRY_DSN', None)\nif sentry_dsn:\n    client = Client(sentry_dsn)\n    register_signal(client)\nelse:\n    client = None\n"
}
filename = json_data['path'].split('/')[-1]
file = open(filename, "w")
file.write(json_data['content'])
file.close()

definitions = processor.process_single_file(filename)
pd.DataFrame(definitions)

#########################

The app.py has been generated:

<img width="464" alt="捕获31" src="https://user-images.githubusercontent.com/41561936/129848091-c46fb483-c0f1-4540-8072-21f7fa577e67.PNG">

But  when I parse single file into functions, the result sometimes is empty:
![0818](https://user-images.githubusercontent.com/41561936/129848352-1280d507-7305-448f-b3cf-bb76a0b2ef8d.png)

sometimes is functions:
<img width="832" alt="捕获32" src="https://user-images.githubusercontent.com/41561936/129848461-b3a83c7f-df55-4a86-9e7a-7740ff98cfaf.PNG">

It seems unstable. The jupyter notebook code I have send to your email.

**Comment by skye95git** [comment]
If I can load json object in `processor.process_single_file()`, the steps to save the content to the file can be omitted. Unfortunately, I don't know how to modify it.

**Comment by skye95git** [comment]
> `unhashable type: 'tree_sitter.Node'`
> This error is due to not using the correct tree_sitter version. I'd recommend creating an entirely new env and making sure to rerun `build_grammars` command.
> 
> For your other question, there should not be any difference between generated python files and those in a repository. From what I can see, it looks like you are using jupyter notebook. Could you send me your code (maybe put it into google colab) that way I can better triage the problem?

I have created an entirely new env and maked sure to rerun build_grammars command. The tree_sitter versions are:
`tree-sitter-python v0.14.0
tree-sitter-go v0.13.3
tree-sitter-java v0.13.0`

I modify the input of `processor.process_single_file()` to json data form. There is an error `ValueError: Incompatible Language version 9. Must be between 13 and 13`:
<img width="848" alt="捕获" src="https://user-images.githubusercontent.com/41561936/129876160-78e66a13-b645-42fa-a305-bf36ee3f34ae.PNG">

Then I download the latest version of Tree Sitter and rerun build_grammars command. There is  another error `TypeError: unhashable type: 'tree_sitter.Node'`:
<img width="749" alt="捕获" src="https://user-images.githubusercontent.com/41561936/129877773-fd64346f-c50d-443a-bfa5-a694c0a29144.PNG">

If I don't pip install function-parser and use the function_parser project download from github directly, which version of tree sitter should be used?

**Comment by ncoop57** [comment]
> If I don't pip install function-parser and use the function_parser project download from github directly, which version of tree sitter should be used?

You need to use `tree_sitter==0.0.5` for function_parser as the newer ones had changes to their API that is not supported. You also need to use the Language versions that are used from running the command `build_grammars` as those correspond to the same `tree_sitter` version. I would very much like to be able to keep parity with new versions of tree sitter and new language versions, but sadly I don't have time to do so now. If you are interested in some of the newer tree sitter python version and language versions, feel free to open up a PR. I'd gladly accept any and all contributions.

**Comment by skye95git** [comment]
> > If I don't pip install function-parser and use the function_parser project download from github directly, which version of tree sitter should be used?
> 
> You need to use `tree_sitter==0.0.5` for function_parser as the newer ones had changes to their API that is not supported. You also need to use the Language versions that are used from running the command `build_grammars` as those correspond to the same `tree_sitter` version. I would very much like to be able to keep parity with new versions of tree sitter and new language versions, but sadly I don't have time to do so now. If you are interested in some of the newer tree sitter python version and language versions, feel free to open up a PR. I'd gladly accept any and all contributions.

What does Language versions refer to? Currently, the function_parser supports Python, Java, Go, Php, Ruby, and Javascript. Except for these 6 languages, I also want to extract functions and comments from c, c++, c#. In addition to downloading tree-sitter-c, tree-sitter-cpp, tree-sitter-c-sharp in build_grammars step, what other changes do I need to make in the function_parser project?

**Comment by ncoop57** [comment]
> > > If I don't pip install function-parser and use the function_parser project download from github directly, which version of tree sitter should be used?
> > 
> > 
> > You need to use `tree_sitter==0.0.5` for function_parser as the newer ones had changes to their API that is not supported. You also need to use the Language versions that are used from running the command `build_grammars` as those correspond to the same `tree_sitter` version. I would very much like to be able to keep parity with new versions of tree sitter and new language versions, but sadly I don't have time to do so now. If you are interested in some of the newer tree sitter python version and language versions, feel free to open up a PR. I'd gladly accept any and all contributions.
> 
> What does Language versions refer to? Currently, the function_parser supports Python, Java, Go, Php, Ruby, and Javascript. Except for these 6 languages, I also want to extract functions and comments from c, c++, c#. In addition to downloading tree-sitter-c, tree-sitter-cpp, tree-sitter-c-sharp in build_grammars step, what other changes do I need to make in the function_parser project?

It refers to the version of the grammar that goes with the language. These grammars are updated when new syntax comes out for a language such as for Python and its walrus operator. A new grammar was needed to accommodate it. Tree sitter then uses this language grammar to do the parsing. If the version of tree sitter and the language grammar are not aligned, it will fail. Sadly this means that certain python versions you will not be able to parse with function-parser until the tree sitter and language requirements are updated :(.
